error: 'X' already exists as an error enum.
  --> tests/trybuild/two_enums_same_name.rs:3:1
   |
3  | / error_set! {
4  | |     X = {
5  | |         IoError2,
6  | |     };
...  |
9  | |     };
10 | | }
   | |_^
   |
   = note: this error originates in the macro `error_set` (in Nightly builds, run with -Z macro-backtrace for more info)
